const state={
 role:'admin', user:'قاسم', trip:'سفر شمال ۱۴۰۵', pendingMembers:[{name:'پرهام رضایی',phone:'09•••',date:'امروز',status:'در انتظار'}], members:[['محمد',1,12000000],['حسین',1,12000000],['قاسم',1,12000000],['احسان',1,12000000],['پگاه',1,12000000],['مهوش',1,12000000],['زهرا',1,12000000],['مهسا',1,10000000],['پریسا',1,10000000],['نهال',.5,5000000],['رایان',.5,2000000]], expenses:[['رستوران ساحلی',2800000,'حسین','در انتظار'],['خرید میوه و تنقلات',1450000,'قاسم','در انتظار'],['بنزین خودرو',1200000,'مهسا','در انتظار'],['گوشت و مواد غذایی',30000000,'صندوق','تأیید شده'],['سوغات شخصی',500000,'محمد','تأیید شده']]};
const $=s=>document.querySelector(s); let modal=()=>document.querySelector('#modal');
const money=n=>new Intl.NumberFormat('fa-IR').format(n)+' تومان';
function renderPending(){ $('#pendingPreview').innerHTML=state.expenses.filter(x=>x[3]==='در انتظار').slice(0,3).map(x=>`<article class="pending-card"><span>🟡</span><div class="grow"><b>${x[0]}</b><small>ثبت توسط ${x[2]} • امروز</small></div><span class="amount">${money(x[1])}</span></article>`).join(''); $('#pendingCount').textContent=state.expenses.filter(x=>x[3]==='در انتظار').length; }
window.showPage=function showPage(page){let title='',body='';
 if(page==='home'){ location.reload(); return; }
 if(page==='expenses'||page==='pending'){title=page==='pending'?'🟡 هزینه‌های در انتظار تأیید':'💰 هزینه‌ها';body=`<div class="filter-row"><button class="chip active">همه</button><button class="chip">🟡 در انتظار</button><button class="chip">🟢 تأیید شده</button><button class="chip">🔴 رد شده</button></div>${state.expenses.map((e,i)=>`<div class="list-item"><span class="badge ${e[3]==='در انتظار'?'pending':'approved'}">${e[3]}</span><b>${e[0]}</b><p>${e[2]} • ${money(e[1])}</p>${state.role==='admin'&&e[3]==='در انتظار'?`<div class="actions"><button class="btn small" onclick="approveExpense(${i})">✓ تأیید</button><button class="btn danger small" onclick="rejectExpense(${i})">× رد</button></div>`:''}</div>`).join('')}<button class="btn" onclick="newExpense()">➕ ثبت هزینه جدید</button>`;
 } else if(page==='fund'){title='🏦 صندوق';body=`<div class="stat primary"><span>موجودی فعلی صندوق</span><strong>۵۸,۵۰۰,۰۰۰</strong><small>تومان</small></div><div class="stat" style="margin-top:10px"><span>📥 مطالبات صندوق</span><strong>۵,۰۰۰,۰۰۰</strong><small>تومان</small></div><button class="btn" onclick="newContribution()">➕ ثبت واریزی به صندوق</button><div class="list-item"><b>تراکنش‌های اخیر</b><p>➕ واریزی تأییدشده محمد — ۱۲,۰۰۰,۰۰۰</p><p>➖ خرید گوشت از صندوق — ۳۰,۰۰۰,۰۰۰</p></div>`;
 } else if(page==='members'){title='👥 اعضای سفر';body=`<button class="btn" onclick="addMember()">➕ افزودن عضو توسط ادمین</button><div class="list-item"><b>🔗 لینک دعوت اعضا</b><p>این لینک را برای اعضای جدید ارسال کنید.</p><button class="btn secondary" onclick="copyInvite()">کپی لینک دعوت</button></div><h3>درخواست‌های عضویت</h3>${state.pendingMembers.map((m,i)=>`<div class="list-item"><span class="badge pending">در انتظار</span><b>${m.name}</b><p>${m.phone} • ${m.date}</p><div class="actions"><button class="btn small" onclick="approveMember(${i})">✓ بررسی و تأیید</button><button class="btn danger small" onclick="rejectMember(${i})">× رد</button></div></div>`).join('')||'<p class="muted">درخواستی وجود ندارد.</p>'}<h3>اعضای فعال</h3>${state.members.map(m=>`<div class="list-item"><b>${m[0]}</b><p>ضریب مشارکت: ${m[1]} • سهم صندوق: ${money(m[2])}</p></div>`).join('')}`;
 } else if(page==='polls'){title='🗳️ رأی‌گیری';body=`<div class="poll-card"><div class="poll-title"><b>فردا کجا برویم؟</b><span>فعال</span></div>${['🌲 جواهرده','🌿 جنگل دالخانی','🌊 رامسر'].map((x,i)=>`<div class="poll-option"><span>${x}</span><b>${[6,4,2][i]} رأی</b></div><div class="bar"><i style="width:${[50,33,17][i]}%"></i></div>`).join('')}<button class="btn">ثبت رأی من</button></div>`;
 } else if(page==='locations'){title='📍 مکان‌های دیدنی';body=['جواهرده','جنگل دالخانی','ساحل رامسر'].map(x=>`<div class="list-item"><b>📍 ${x}</b><p>مکان پیشنهادی سفر</p><button class="btn">پیشنهاد برای رأی‌گیری</button></div>`).join('');
 } else if(page==='itinerary'){title='🗺️ برنامه سفر';body=['۱۰:۰۰ — 📍 جواهرده','۱۴:۳۰ — 🍽️ ناهار','۱۷:۰۰ — 🌊 ساحل رامسر','۲۰:۰۰ — 🏠 بازگشت'].map(x=>`<div class="list-item" ${x.startsWith('📷')?'onclick="showPage(\'album\')"':''}><b>${x}</b></div>`).join('');
 } else if(page==='settlement'){title='💸 تسویه حساب هوشمند';body=`<div class="stat primary"><span>وضعیت تسویه</span><strong>۳ انتقال</strong><small>برای تسویه کامل</small></div>${[['محمد','+۳,۲۰۰,۰۰۰','طلبکار'],['حسین','−۱,۸۰۰,۰۰۰','بدهکار'],['مهسا','−۱,۴۰۰,۰۰۰','بدهکار']].map(x=>`<div class="list-item"><b>${x[0]}</b><span class="badge ${x[2]==='طلبکار'?'approved':'pending'}">${x[2]}</span><p>${x[1]} تومان</p></div>`).join('')}`;
 } else if(page==='album'){title='📷 آلبوم سفر';body=`<div class="album-toolbar"><p class="muted">اعضای فعال سفر می‌توانند عکس اضافه کنند، لایک کنند و نظر بگذارند.</p><button class="btn" onclick="uploadPhoto()">📤 آپلود عکس</button></div><div id="albumGrid" class="album-grid"><div class="empty-state">در حال بارگذاری آلبوم...</div></div>`; setTimeout(loadAlbum,0);
 } else if(page==='profile'){title='👤 پروفایل';const u=window.authState?.profile, m=window.authState?.member;body=`<div class="profile-card"><div class="profile-avatar">${(u?.display_name||state.user||'ق').slice(0,1)}</div><h3>${u?.display_name||state.user||'کاربر'}</h3><p>${u?.phone||'شماره موبایل ثبت نشده'}</p><p>${window.authState?.session?.user?.email||'ایمیل ثبت نشده'}</p><span class="badge ${m?.role==='admin'?'approved':'pending'}">${m?.role==='admin'?'👑 مدیر سفر':'👤 عضو سفر'}</span></div><div class="list-item"><b>🧳 سفر فعال</b><p>${window.authState?.trip?.title||state.trip}</p></div>${m?.role==='admin'?'<button class="btn" onclick="showPage(\'admin\')">👑 پنل مدیریت</button>':''}${window.authState?.session?'<button class="btn danger" onclick="logoutUser()">خروج از حساب</button>':'<button class="btn" onclick="showAuth()">ورود / ایجاد حساب</button>'}`;
} else if(page==='admin'){title='👑 پنل مدیریت';body=`<div class="admin-grid"><button onclick="showPage('members')">👥<b>اعضا</b><small>عضویت و ضرایب</small></button><button onclick="showPage('pending')">🟡<b>درخواست‌ها</b><small>تأیید هزینه‌ها</small></button><button onclick="newTrip()">🧳<b>سفر جدید</b><small>ایجاد سفر مستقل</small></button><button>📊<b>گزارش‌ها</b><small>Excel / PDF</small></button></div>`;
 } else {title='☰ امکانات بیشتر';body=['📷 آلبوم عکس','🎒 چک‌لیست سفر','🔔 اعلان‌ها','📊 گزارش‌ها و نمودارها','⚙️ تنظیمات'].map(x=>`<div class="list-item" ${x.startsWith('📷')?'onclick="showPage(\'album\')"':''}><b>${x}</b></div>`).join('')+(state.role==='admin'?`<div class="list-item" onclick="showPage('admin')"><b>👑 پنل مدیریت</b><p>مدیریت اعضا، تأییدها و سفرها</p></div>`:'');}
 const target=document.querySelector('#app'); if(target){target.innerHTML=`<button class="back-home" onclick="showPage('home')">← بازگشت به داشبورد</button><section class="page-panel"><h2>${title}</h2>${body}</section>`; window.scrollTo({top:0,behavior:'smooth'}); } }
window.closeModal=function closeModal(){modal().classList.add('hidden')}
function approveExpense(i){state.expenses[i][3]='تأیید شده';showPage('pending');renderPending()};function rejectExpense(i){state.expenses[i][3]='رد شده';showPage('pending');renderPending()};
function approveMember(i){const m=state.pendingMembers[i];modal().innerHTML=`<div class="sheet"><button class="close" onclick="closeModal()">×</button><h2>تأیید عضویت</h2><div class="form"><label>نام عضو<input id="mn" value="${m.name}"></label><label>ضریب مشارکت<input id="mw" type="number" step="0.1" value="1"></label><label>سهم هدف صندوق<input id="mc" type="number" value="12000000"></label><label>نقش<select id="mr"><option>کاربر</option><option>ادمین</option></select></label><button class="btn" onclick="activateMember(${i})">✓ تأیید و فعال‌سازی</button></div></div>`;}
function activateMember(i){const n=$('#mn').value,w=Number($('#mw').value),c=Number($('#mc').value);state.members.push([n,w,c]);state.pendingMembers.splice(i,1);showPage('members')}
function rejectMember(i){state.pendingMembers.splice(i,1);showPage('members')}
function addMember(){modal().innerHTML=`<div class="sheet"><button class="close" onclick="closeModal()">×</button><h2>➕ افزودن عضو</h2><div class="form"><label>نام و نام خانوادگی<input id="an"></label><label>شماره موبایل<input id="ap"></label><label>ضریب مشارکت<input id="aw" type="number" step="0.1" value="1"></label><label>سهم هدف صندوق<input id="ac" type="number" value="12000000"></label><button class="btn" onclick="saveMember()">ایجاد کاربر</button></div></div>`}
function saveMember(){state.members.push([$('#an').value,Number($('#aw').value),Number($('#ac').value)]);showPage('members')}
function newExpense(){alert('فرم ثبت هزینه در نسخه متصل به Supabase فعال می‌شود.')};function newContribution(){alert('فرم واریزی در نسخه متصل به Supabase فعال می‌شود.')};window.newTrip=()=>{const m=document.querySelector('#modal');m.innerHTML=`<div class="sheet"><button class="close" onclick="closeModal()">×</button><h2>🧳 ایجاد سفر جدید</h2><div class="form"><label>عنوان سفر<input id="ntTitle" placeholder="مثلاً سفر شمال ۱۴۰۵"></label><label>مقصد<input id="ntDest" placeholder="شمال ایران"></label><label>تاریخ شروع<input id="ntStart" type="date"></label><label>تاریخ پایان<input id="ntEnd" type="date"></label><label>موجودی اولیه صندوق<input id="ntFund" type="number" value="0"></label><label>نام مدیر<input id="ntName" value="${window.authState?.profile?.display_name||''}"></label><label>سهم هدف صندوق مدیر<input id="ntContrib" type="number" value="0"></label><button class="btn" onclick="createTrip()">ایجاد سفر و مدیر شدن</button></div></div>`;m.classList.remove('hidden')};
window.createTrip=async()=>{if(!window.authState?.session){showAuth();return;}const g=id=>document.getElementById(id)?.value||null;const {data,error}=await window.sb.rpc('create_trip_with_admin',{p_title:g('ntTitle'),p_destination:g('ntDest'),p_start_date:g('ntStart')||null,p_end_date:g('ntEnd')||null,p_opening_fund:Number(g('ntFund')||0),p_name:g('ntName'),p_phone:window.authState.profile?.phone||null,p_share_weight:1,p_contribution_target:Number(g('ntContrib')||0)});if(error){alert(error.message);return;}alert('سفر با موفقیت ایجاد شد و شما مدیر سفر شدید.');location.href=location.pathname;};
window.copyInvite=async()=>{if(!window.authState?.tripId){alert('ابتدا یک سفر ایجاد یا انتخاب کنید.');return;}const {data,error}=await window.sb.rpc('create_trip_invite',{p_trip_id:window.authState.tripId,p_expires_at:null});if(error){alert(error.message);return;}const url=location.origin+location.pathname+'?join='+data;try{await navigator.clipboard.writeText(url);alert('لینک دعوت کپی شد.');}catch(e){prompt('لینک دعوت:',url)}}
window.refreshAppAuth=()=>{const a=document.querySelector('.avatar');if(!a)return;a.textContent=window.authState?.session?'✓':'ق';};
window.showAccount=()=>{const m=document.querySelector('#modal');const u=window.authState?.profile;m.innerHTML=`<div class="sheet"><button class="close" onclick="closeModal()">×</button><h2>👤 حساب کاربری</h2><div class="list-item"><b>${u?.display_name||'کاربر'}</b><p>${u?.phone||''}</p><p>${window.authState?.member?.role==='admin'?'👑 مدیر سفر':'👤 عضو سفر'}</p></div><button class="btn danger" onclick="logoutUser()">خروج از حساب</button></div>`;m.classList.remove('hidden');};


window.uploadPhoto=async()=>{
 if(!window.authState?.session){showAuth();return;}
 const input=document.createElement('input'); input.type='file'; input.accept='image/*';
 input.onchange=async()=>{const file=input.files?.[0]; if(!file)return; if(file.size>8*1024*1024){alert('حداکثر حجم عکس ۸ مگابایت است.');return;} if(!window.authState.tripId){alert('ابتدا عضو یک سفر شوید.');return;}
  const path=`${window.authState.tripId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;
  const {error:up}=await window.sb.storage.from('trip-photos').upload(path,file,{upsert:false,contentType:file.type}); if(up){alert('آپلود عکس انجام نشد: '+up.message);return;}
  const {data:pub}=window.sb.storage.from('trip-photos').getPublicUrl(path);
  const {error}=await window.sb.from('album_photos').insert({trip_id:window.authState.tripId,user_id:window.authState.session.user.id,storage_path:path,photo_url:pub.publicUrl,caption:''}); if(error){alert('ثبت عکس انجام نشد: '+error.message);return;} loadAlbum();
 }; input.click();
};
window.togglePhotoLike=async(photoId)=>{if(!window.authState?.session){showAuth();return;} const {data:existing}=await window.sb.from('photo_likes').select('id').eq('photo_id',photoId).eq('user_id',window.authState.session.user.id).maybeSingle(); if(existing){await window.sb.from('photo_likes').delete().eq('id',existing.id);}else{const {error}=await window.sb.from('photo_likes').insert({photo_id:photoId,user_id:window.authState.session.user.id});if(error){alert(error.message);return;}} loadAlbum();};
window.addPhotoComment=async(photoId)=>{if(!window.authState?.session){showAuth();return;} const text=prompt('نظر شما:'); if(!text?.trim())return; const {error}=await window.sb.from('photo_comments').insert({photo_id:photoId,user_id:window.authState.session.user.id,comment:text.trim()});if(error){alert(error.message);return;} loadAlbum();};
window.loadAlbum=async()=>{const grid=document.querySelector('#albumGrid');if(!grid)return;if(!window.authState?.tripId){grid.innerHTML='<div class="empty-state">برای دیدن آلبوم ابتدا وارد حساب شوید و عضو سفر باشید.</div>';return;} const {data:photos,error}=await window.sb.from('album_photos').select('id,photo_url,caption,created_at,user_id,profiles(display_name),photo_likes(id,user_id),photo_comments(id,comment,created_at,user_id,profiles(display_name))').eq('trip_id',window.authState.tripId).order('created_at',{ascending:false}); if(error){grid.innerHTML=`<div class="empty-state">آلبوم هنوز در دیتابیس فعال نشده است.<br><small>${error.message}</small></div>`;return;} grid.innerHTML=(photos||[]).map(ph=>{const liked=(ph.photo_likes||[]).some(x=>x.user_id===window.authState.session?.user?.id);const comments=(ph.photo_comments||[]).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).slice(-3);return `<article class="photo-card"><img src="${ph.photo_url}" loading="lazy" alt="عکس سفر"><div class="photo-meta"><b>${ph.profiles?.display_name||'عضو سفر'}</b><div class="photo-actions"><button class="icon-btn ${liked?'liked':''}" onclick="togglePhotoLike('${ph.id}')">♥ ${(ph.photo_likes||[]).length}</button><button class="icon-btn" onclick="addPhotoComment('${ph.id}')">💬 ${(ph.photo_comments||[]).length}</button></div></div>${ph.caption?`<p>${ph.caption}</p>`:''}<div class="comments">${comments.map(c=>`<div><b>${c.profiles?.display_name||'عضو'}:</b> ${String(c.comment).replace(/[&<>]/g,'')}</div>`).join('')}</div></article>`}).join('')||'<div class="empty-state">هنوز عکسی در آلبوم نیست. اولین عکس را شما اضافه کنید 📸</div>';};

document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)showPage(b.dataset.page);if(e.target===modal)closeModal()});renderPending();
