-- v13.3 FIX: invite-based self registration + admin approval
-- Safe to run after the previous v13.3 migration failed.
-- This migration first creates membership_requests, then creates the RPCs.

create table if not exists public.membership_requests (
  id bigint generated by default as identity primary key,
  trip_id uuid not null references public.trips(id) on delete cascade,
  invite_id uuid null,
  user_id uuid not null references auth.users(id) on delete cascade,
  full_name text not null,
  phone text,
  note text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  requested_at timestamptz not null default now(),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  rejection_reason text
);

create index if not exists membership_requests_trip_status_idx
  on public.membership_requests(trip_id, status, requested_at desc);

create index if not exists membership_requests_user_trip_idx
  on public.membership_requests(user_id, trip_id);

alter table public.membership_requests enable row level security;

drop policy if exists "membership_requests_select_members" on public.membership_requests;
drop policy if exists "membership_requests_insert_own" on public.membership_requests;
drop policy if exists "membership_requests_admin_update" on public.membership_requests;

-- Admins can see requests for their trip; a requester can see their own request.
create policy "membership_requests_select_members"
on public.membership_requests
for select
to authenticated
using (
  user_id = auth.uid()
  or public.is_trip_admin(trip_id)
);

-- A signed-in user can submit a request only for themselves.
create policy "membership_requests_insert_own"
on public.membership_requests
for insert
to authenticated
with check (
  user_id = auth.uid()
  and status = 'pending'
);

-- Normal clients do not update requests directly; admin RPCs below do it securely.
create policy "membership_requests_admin_update"
on public.membership_requests
for update
to authenticated
using (public.is_trip_admin(trip_id))
with check (public.is_trip_admin(trip_id));

-- Prevent duplicate pending requests for the same user/trip.
create unique index if not exists membership_requests_one_pending_idx
  on public.membership_requests(trip_id, user_id)
  where status = 'pending';

create or replace function public.approve_membership_request(
  p_request_id bigint,
  p_name text,
  p_share_weight numeric default 1,
  p_contribution_target bigint default null,
  p_role public.trip_member_role default 'member'::public.trip_member_role
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.membership_requests%rowtype;
  v_member_id bigint;
  v_share_amount bigint;
  v_weight numeric;
begin
  select * into r
  from public.membership_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception 'درخواست عضویت پیدا نشد';
  end if;

  if not public.is_trip_admin(r.trip_id) then
    raise exception 'فقط مدیر سفر می‌تواند درخواست عضویت را تأیید کند';
  end if;

  if r.status <> 'pending' then
    raise exception 'این درخواست قبلاً بررسی شده است';
  end if;

  if exists (
    select 1 from public.trip_members
    where trip_id = r.trip_id
      and user_id = r.user_id
      and active = true
  ) then
    raise exception 'این کاربر قبلاً عضو فعال این سفر است';
  end if;

  v_weight := coalesce(p_share_weight, 1);
  if v_weight <= 0 then
    raise exception 'ضریب مشارکت باید بیشتر از صفر باشد';
  end if;

  select coalesce(share_amount, 12000000)
    into v_share_amount
  from public.trips
  where id = r.trip_id;

  insert into public.trip_members (
    trip_id,
    user_id,
    name,
    role,
    share_weight,
    contribution_target,
    active
  ) values (
    r.trip_id,
    r.user_id,
    coalesce(nullif(trim(p_name), ''), r.full_name),
    coalesce(p_role, 'member'::public.trip_member_role),
    v_weight,
    round(v_weight * v_share_amount)::bigint,
    true
  )
  returning id into v_member_id;

  update public.membership_requests
  set status = 'approved',
      reviewed_by = auth.uid(),
      reviewed_at = now()
  where id = p_request_id;

  return v_member_id;
end;
$$;

grant execute on function public.approve_membership_request(bigint,text,numeric,bigint,public.trip_member_role)
to authenticated;

create or replace function public.reject_membership_request(
  p_request_id bigint,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_trip uuid;
  v_status text;
begin
  select trip_id, status
    into v_trip, v_status
  from public.membership_requests
  where id = p_request_id
  for update;

  if v_trip is null then
    raise exception 'درخواست عضویت پیدا نشد';
  end if;

  if not public.is_trip_admin(v_trip) then
    raise exception 'فقط مدیر سفر می‌تواند درخواست عضویت را رد کند';
  end if;

  if v_status <> 'pending' then
    raise exception 'این درخواست قبلاً بررسی شده است';
  end if;

  update public.membership_requests
  set status = 'rejected',
      rejection_reason = nullif(trim(coalesce(p_reason, '')), ''),
      reviewed_by = auth.uid(),
      reviewed_at = now()
  where id = p_request_id;
end;
$$;

grant execute on function public.reject_membership_request(bigint,text)
to authenticated;

notify pgrst, 'reload schema';
